### ISSUE TITLE
When StopBrowse() method is called ServiceRemoved events are raised on all the previously added services

### ISSUE THREAD

**Issue by kgullapali** [tmds/Tmds.MDns#12]
Hi,

I am running a simple test of stopping the service browser and this is my code:
            serviceBrowser.StartBrowse(serviceType);
            Thread.Sleep(1000);
            serviceBrowser.StopBrowse();
All the services that the ServiceBrowser found and notified by ServiceAdded event are being removed. 
I tried to trace it back to Public void Disable() function in the NetworkInterfaceHandler.cs

Could you please clarify if this is correct behavior or am I doing something wrong?

My intention is to perform the MDns discovery for a period of time and stop the discovery.

Thank you.

**Comment by tmds** [comment]
This is intentional.

**Comment by kgullapali** [comment]
Could you please suggest me how I can stop browsing and still keep my previously discovered services

**Comment by tmds** [comment]
Add the ServiceAnnouncements to a List and don't remove them.

**Comment by kgullapali** [comment]
In other words I need to ignore the ServiceRemoved events that my handler receives after the StopBrowse () function call. Is that correct?

**Comment by tmds** [comment]
That is what you want.

**Comment by kgullapali** [comment]
Thank you very much for the help and you really did a great work on your tmds mDns library, it's very helpful.

**Comment by tmds** [comment]
Thanks! have a nice day :)
