### ISSUE TITLE
_socket.SendTo function throws excption  in Mac OS 10.11.6 (mono 4.6.0)

### ISSUE THREAD

**Issue by sushmakoulgi** [tmds/Tmds.MDns#13]
_socket.SendTo function throws exception ("Address is not valid in the current context) in Mac OS 10.11.6 (mono 4.6.0)

**Comment by tmds** [comment]
This is fixed on master: https://github.com/tmds/Tmds.MDns/commit/21007010f355fe54f1e8f4785dd5c8cf49f6bbcc

**Comment by tmds** [comment]
can you check with master?

**Comment by sushmakoulgi** [comment]
@tmds . interface check is present in the code. Looks like problem is with specific version of mono (4.2.2.3)

I just upgraded to 4.6.2 , issue no longer persists. Thanks for the quick response.
