### ISSUE TITLE
Support for _services._dns-sd._udp.local ?

### ISSUE THREAD

**Issue by NoelAnderson** [tmds/Tmds.MDns#25]
According to the RFC "_services._dns-sd._udp" is a special meta-query for discovering all services.  Does this library support this?  A quick test with the service Finder sample didn't seem to return any results

**Comment by tmds** [comment]
The implementation was is written to find types you know up-front. If this needs extra handling, then it is probably not supported.

**Comment by tmds** [comment]
Closing since no plans to implement this feature.
