### ISSUE TITLE
Compatibility with Universal Windows Platform (UWP)

### ISSUE THREAD

**Issue by Horcrux7** [tmds/Tmds.MDns#7]
Is it possible to make the NuGet package compatible with UWP? My understanding is that it must based on .NETStandard 1.4 instead of .NETStandard 1.5.

https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md

**Comment by tmds** [comment]
Probably netstandard 1.3 would work too.
I think it is a matter of adjusting https://github.com/tmds/Tmds.MDns/blob/039c84bd25cb25a474fe20ea448757fa6c630455/src/Tmds.MDns/project.json: netstandard1.5 -> netstandard1.3
and https://github.com/tmds/Tmds.MDns/blob/6a5451278ff0fbe97faf5b1afb0bae884dbfa8ff/src/Tmds.MDns/NetworkInterfaceHandler.cs: NETSTANDARD1_5 -> NETSTANDARD1_3
You can send me a pull request or I'll have a look during the weekend.

**Comment by tmds** [comment]
Published v0.6.0 https://www.nuget.org/packages/Tmds.MDns/0.6.0 targetting netstandard1.3

**Comment by Horcrux7** [comment]
Thanks for the very fast implementing this.

**Comment by tmds** [comment]
No problem. Feel free to add a star :)

Op 26-jul.-2016 16:36 schreef "Volker Berlin" <notifications@github.com>:
